export const APP_CLICK = 'APP_CLICK'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_RECEIVE = 'GET_USERS_RECEIVE'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_RECEIVE = 'GET_USER_RECEIVE'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
